POST http://{{host}}/login_j
Content-Type: application/json

{
"username": "narata",
"password": "narata"
}

###
POST http://{{host}}/house/test
Content-Type: application/json
Cookie: {{cookie}}

{
  "size": 123,
  "location": "",
  "rent": "",
  "floor": ""
}

###