POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username=narata&password=narata

###
GET http://{{host}}/hello

###
POST http://{{host}}/login_j
Content-Type: application/json

{
"username": "narata",
"password": "narata"
}

###
GET http://{{host}}/logout
Cookie: {{cookie}}

###
GET http://{{host}}/hello_login
Cookie: {{cookie}}

###
POST http://{{host}}/register
Content-Type: application/json
Cookie: {{cookie}}

{
  "username": "lemontong",
  "password": "jt09101025"
}
###
POST http://{{host}}/daily/create
Content-Type: application/json
Cookie: {{cookie}}

{
  "title": "test1",
  "data": "test1"
}

###
GET http://{{host}}/daily?current=1&size=2&self=true
Cookie: {{cookie}}

###
GET http://{{host}}/daily?current=3&size=10&self=false
Cookie: {{cookie}}

###
PATCH http://{{host}}/daily
Cookie: {{cookie}}
Content-Type: application/json

{
  "id": 2,
  "title": "test1_edit",
  "data": "test1_edit"
}

###

GET http://{{host}}/daily?self=true&current=1&size=10
Cookie: {{cookie}}

###

DELETE http://{{host}}/daily?id=6
Cookie: {{cookie}}
Content-Type: application/json

###
GET http://{{host}}/1.jpg
Cookie: {{cookie}}

###
POST http://{{host}}/image
Cookie: {{cookie}}

###